modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/MC-U-Team/Attack-Speed-Enchantment/issues"
license="Apache-2.0 License"

[[mods]]
	modId="attackspeedenchantment"
	version="${file.jarVersion}"
	displayName="Attack Speed Enchantment"
	displayURL="https://u-team.info/mods/attackspeedenchantment"
	updateJSONURL="https://api.u-team.info/update/attackspeedenchantment.json"
	logoFile="logo.png"
	credits="Team U-Team"
	authors="HyCraftHD"
	description="Join our discord server here: https://discord.hycrafthd.net\n\nThis mod adds an enchantment that allows you to decrease the attack cooldown. When the enchantment reaches Level 10 the cooldown is removed entirely."
	
	[[dependencies.attackspeedenchantment]]
	    modId="forge"
	    mandatory=true
	    versionRange="[47.0.35,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.attackspeedenchantment]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.20.1]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.attackspeedenchantment]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[5.1.3.267,)"
	    ordering="NONE"
	    side="BOTH"